language: node_js

node_js:
  - 12

install:
  - npm install

script:
  - npm run sass:build

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, https://github.com/settings/tokens
  on:
    branch: master
